name: demo-workflow

on:
  push:
    branches: main

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: sample job
      run: echo "HelloWorld"
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.0
      with:   
        name: sample job  
        path: ${{github.workspace}}
  deploy:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - uses: actions/download-artifact@v4
          with:
            name: sample job
            path: ${{github.workspace}}

